### ISSUE TITLE
Hypergraph creation

### ISSUE THREAD

**Issue by PXThanhLam** [anguoyuan/Hypergraph-Propagation-and-Community-Selection-for-Objects-Retrieval#1]
Hi authors, awesome work and impressive result, which is current sota and beat the previous approach by a large margin. Could you give the script to create the hypergraph (which is only available now via downloading) from the local and global descriptors? And what exactly are Match_region and Match_loc in your graph.zip. As I read your paper and code, Match_region seems to be the region to calculate the intra edge of the graph, and Match_loc is the matching local between two images. If I'm right, is the shape 9x2 in the Match_loc  the index of matching local descriptors between two images. Thank you.

**Comment by anguoyuan** [comment]
Hi, thank you for your interest in our work! Actually, the hypergraph is computed in real-time after the query is given and the code is already included in hypergraph_propagation.py. Graph file contains the ordinary knn graph (Neighbors) and the pre-computed matching information. You can understand Match_region and Match_Loc (matched points' locations) as the precomputed homograph between two images using RANSAC. We do not save the homograph matrix itself but store the matched points' regions and locations. More specifically, for the key 'imlist_1_imlist_2', Match_region and Match_loc are the region and locations of the matched points in imlist_2. There is also a key 'imlist_2_imlist_1' to store the region and location of the matched points in image1.  They are calculated offline using RANSAC with the same setting with Cao's DELG paper . We will give the off-line RANSAC code to calculate the Match_region and Match_Loc soon. I hope this answer will help you.

**Comment by PXThanhLam** [comment]
Thank you for your answer. Looking for your RANSAC code to calculate the Match_region and Match_loc.

**Comment by anguoyuan** [comment]
Hi, we just uploaded the offline RANSAC code. Please check it and contact us if you get any questions. We also welcome more comments about our paper.
